Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/precise32"
    config.vm.define :web do |web_config|
        #web_config.vm.network "private_network", ip: "192.168.0.33"
        web_config.vm.network "public_network", :bridge => "en0: Wi-Fi (Airport)", :ip => "192.168.0.33"
    end
end